server:
  port: 9988
spring:
  application:
    name: ace-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: study-git
          uri: http://127.0.0.1:9999
          predicates:
            - Path=/hello/**
            - Cookie=chocolate, 123456
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
            - AddRequestParameter=foo, bar

    consul:
      port: 8500
      host: 127.0.0.1
      discovery:
        prefer-ip-address: true