server:
  port: 8998
spring:
  datasource:
    url: jdbc:mysql://mysql.server.fjf:3308/xry?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: foxconn.88
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  data:
    mongodb:
      database: gg
      username: gg
      password: gg123
      host: 193.112.111.196
      port: 27017
#mongo多数据源配置
#mongodb:
#  mmProperties:
#      database: mm
#      username: mm
#      password: mm123
#      host: 193.112.111.196
#      port: 27017
#  ggProperties:
#      database: gg
#      username: gg
#      password: gg123
#      host: 193.112.111.196
#      port: 27017
mybatis:
  mapper-locations: classpath:mapper/*.xml